resolved product interface and added remaining restful endpoints
JohanTran02/IMS pull request #35
Opened 2024-09-10 13:14 UTC by GaKa00

same issue, locally  res.json appears as null. pls test mr Johan D:

2024-09-10 17:53 UTC, JohanTran02 requested changes
Jag kommenterade på funktionerna som inte funka. Kolla på de så kan jag kika igen att allt inte knasar till med null. Allt ser riktigt snyggt annars!!!! 💯

2024-09-10 17:53 UTC, JohanTran02 commented on backend/resources/product/types.ts
Det ska nog vara små bokstäver i början. Verkar krångla till med typerna när man skriver variablerna. Kommer skapa en issue för det.

2024-09-10 17:53 UTC, JohanTran02 commented on backend/resources/product/types.ts
>  export interface IProduct {
Märker också att det är problem med mongoose Schema om man explicit lägger till en _id egenskap behöver man alltid generera ett eget id. Det är bättre om vi tar bort egenskapen så att MongoDB skapar ett id automatiskt. Därför blir det problem när man kör: `router.post("/api/product", postProduct);`.

2024-09-10 17:53 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +     return total * product.price;   //might  have to change  Iproduct (product.price ) to number
```suggestion
return total + product.price * product.amountInStock; 
```

2024-09-10 17:53 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +                    StockValue: { $sum: { $multiply: ["$price", "$quantity"] } }
```suggestion
                    StockValue: { $sum: { $multiply: ["$price", "$amountInStock"] } } 
```

2024-09-11 07:47 UTC, GaKa00 commented on backend/resources/product/products.controller.ts
> +     return total * product.price;   //might  have to change  Iproduct (product.price ) to number
resolved

2024-09-11 08:06 UTC, GaKa00 commented on backend/resources/product/types.ts
>  export interface IProduct {
resolved #36

2024-09-11 08:07 UTC, GaKa00 commented on backend/resources/product/products.controller.ts
> +                    StockValue: { $sum: { $multiply: ["$price", "$quantity"] } }
resolved

2024-09-11 08:08 UTC, GaKa00 commented on backend/resources/product/types.ts
resolved

2024-09-11 08:23 UTC, JohanTran02 commented
Gör en pull request till feature/restendpoints

2024-09-11 08:23 UTC, closed without merging