GaKa00/issue42
JohanTran02/IMS pull request #48
Opened 2024-09-16 12:18 UTC by GaKa00

Fixes #42 and bool error #43

2024-09-16 12:44 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +      } : { $sort: { amountInStock: 1 } }
```suggestion
    $sort: { amountInStock: bool  }
```

2024-09-16 12:46 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 12:46 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 12:46 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 12:47 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 12:48 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 12:49 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 12:49 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 12:50 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 12:52 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion     
        { $sort: { amountInStock: -1  }}
```

2024-09-16 12:53 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
    
      
             { $sort: { amountInStock: -1  }}
      
```

2024-09-16 12:54 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
            { $sort: { amountInStock: -1  }}
```

2024-09-16 12:56 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
        { $sort: { amountInStock: -1  }}
    
```

2024-09-16 12:58 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      bool ? {
        $sort: { amountInStock: -1  }
      } : { $sort: { amountInStock: 1 } }
```     { $sort: { amountInStock: -1  }}

2024-09-16 12:59 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
{ $sort: { amountInStock: -1  }}
```

2024-09-16 13:01 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
            { $sort: { amountInStock: -1  }}
```

2024-09-16 13:03 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
     { $sort: { amountInStock: -1  }}
    ]);
```

2024-09-16 13:03 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +      } : { $sort: { amountInStock: 1 } }
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 13:04 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +          amountInStock: { $first: "$amountInStock" },
```suggestion
     test
```

2024-09-16 13:04 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +      } : { $sort: { amountInStock: 1 } }
```suggestion
     { $sort: { amountInStock: -1  }}
```

2024-09-16 13:29 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      {
        $group: {
          _id: "$_id",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
      },
```

2024-09-16 13:29 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      {
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
      },
```

2024-09-16 13:30 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      {
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
      },
```

2024-09-16 13:30 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      {
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
      },
```

2024-09-16 13:31 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      {
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
      },
```

2024-09-16 13:31 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      {
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
      },
```

2024-09-16 13:31 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      {
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
      },
```

2024-09-16 13:32 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      {
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
      },
```

2024-09-16 13:33 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
```

2024-09-16 13:33 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
      {
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
      },
```

2024-09-16 13:34 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
        $group: {
          _id: "$name",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
```

2024-09-16 13:35 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
    $group: {
        _id: "$name",
        name: { $first: "$name" },
        amountInStock: { $first: "$amountInStock" },
    },
```

2024-09-16 13:35 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
            $group: {
            _id: "$name",
            name: { $first: "$name" },
            amountInStock: { $first: "$amountInStock" },
            },
```

2024-09-16 13:37 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
        { $sort: { amountInStock: bool } }
```

2024-09-16 13:37 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
        { $sort: { amountInStock: 1 } }]);
```

2024-09-16 13:38 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
{ $sort: { amountInStock: 1 } }
```

2024-09-16 13:38 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
{ $sort: { amountInStock: bool } }
```

2024-09-16 13:39 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +}
```suggestion
        { $sort: { amountInStock: bool } }]);
```

2024-09-16 13:40 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +      } : { $sort: { amountInStock: 1 } }
```suggestion
    { $sort: { amountInStock: bool } }
```

2024-09-16 13:40 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +        },
```suggestion
        $group: {
          _id: "$_id",
          name: { $first: "$name" },
          amountInStock: { $first: "$amountInStock" },
        },
```

2024-09-16 13:43 UTC, JohanTran02 commented on backend/resources/product/products.controller.ts
> +  } catch (err) {
Mappen uppnår samma sak som aggregation #L211-218

2024-09-16 13:57 UTC, JohanTran02 requested changes
Only really tiny changes. Dont forget to pull from main before committing or merging. Otherwise very nice code!!!!

2024-09-17 07:36 UTC, GaKa00 commented on backend/resources/product/products.controller.ts
> +        },
applied suggestion

2024-09-17 08:12 UTC, JohanTran02 approved these changes
Funkar!

2024-09-17 08:12 UTC, merged